version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres-banking
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
